version: '3'

services:
  saimon:
    build: .
    restart: unless-stopped
    ports:
      - 8001:8080
    deploy:
      resources:
        reservations:
          devices:
          -  driver: nvidia
             count: all
             capabilities: [gpu]