# use text gen webUI as the LLM
llm:
  mode: openailike

embedding:
  mode: local
  ingest_mode: simple

local:
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

openai:
  api_base:  http://127.0.0.1:5000/v1
  api_key: EMPTY
  model: mistral-7b-instruct-v0.2.Q5_K_M.gguf