server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /

llm:
  mode: mock

local:
  model_file: llama-2-7b-chat.Q4_0.gguf
  persist_dir: ./storage

sagemaker:
  endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140

openai:
  api_key: ${OPENAI_API_KEY:}
