server:
  env_name: staging
  port: ${PORT:8080}

llm:
  mode: ${PGPT_INFERENCE_MODE:openai}

embedding:
  mode: ${PGPT_EMBEDDING_MODE:openai}

ui:
  enabled: false

qdrant:
  url: ${QDRANT_URL}
  api_key: ${QDRANT_API_KEY}

openai:
  api_key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
