server:
  env_name: ${APP_ENV:ollama}

llm:
  mode: ollama
  max_new_tokens: 512
  context_window: 3900

embedding:
  mode: ollama

ollama:
  llm_model: mistral
  embedding_model: nomic-embed-text
  api_base: http://localhost:11434

vectorstore:
  database: qdrant

indexstore:
  mode: mongo
  host: mongodb+srv://unfreeze-gmk:y9t9mJBdhECC1BBq@unfreeze-pggpt-gmk.wh9chmw.mongodb.net/?retryWrites=true&w=majority&appName=unfreeze-pggpt-gmk
  port: 27017

qdrant:
  path: local_data/private_gpt/qdrant
